[build]
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/opt/buildhome/repo"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 